### ISSUE TITLE
rg-workload deployments does not even start to deploy

### ISSUE THREAD

**Issue by RogerQwerty** [mattfeltonma/azure-labs#67]
In reference to [azure-labs](https://github.com/mattfeltonma/azure-labs)/appgw-hub-spoke/ it looks like the rg-workload deployments does not even start to deploy. Note I am not seeing any errors code, nothing.

In my deployment rg-shared & rg-transit finished with no issues. They look good.

In the rg-worload resource nothing is listed under the deployment section.
![2023-05-06 11_44_50-Window](https://user-images.githubusercontent.com/24612540/236636662-42c97de0-b28b-4d50-b15c-f566082a0da5.png)
![2023-05-06 11_45_23-Window](https://user-images.githubusercontent.com/24612540/236636689-7bef4950-95a6-44e4-86db-f038f71f9b08.png)
![2023-05-06 11_45_35-Window](https://user-images.githubusercontent.com/24612540/236636704-14fb8df3-c00f-487a-87be-877b0febddf8.png)

**Comment by mattfeltonma** [comment]
Hi there. You need to check the deployment at your subscription level, not at the resource group level. You likely have an error there due to a missing permission or a policy prohibiting you from moving the deployment forward.

**Comment by mattfeltonma** [comment]
I did a test this afternoon deploying this lab via the "Deploy to Azure" button and it deployed successfully. I'd suggest your review your deployments at the Subscription scope. You likely have a failure due to policy or missing permission. When you are looking for deployments at the Subscription level, take note that they're not always in order by date. You may have to search through for yours.

**Comment by RogerQwerty** [comment]
ok, I will dig through it. Thanks for the response.
